<header>
    <div class="menu">
        <nav>
            <ul class="nav-menu">
                <li><a class="nav-link" href="index.html"><span id="home">Home</span></a></li>
                <li><a class="nav-link" href="jobs.html"><span id="careers">Careers</span></a></li>
                <li><a class="nav-link" href="apply.html"><span id="join-us">Join Us</span></a></li>
                <li><a class="nav-link" href="about.html"><span id="about-us">About Us</span></a></li>
                <li><a class="nav-link" href="enhancements.html"><span id="enhancements">Enhancements</span></a>
                </li>
            </ul>
        </nav>
        <a class="button" href="mailto:103076428@student.swin.edu.au">
            <span id="contact-us">Contact Us</span>
        </a>
    </div>
</header>