<div id="logo-container">
    <a href="index.php"><img id="logo" src="images/fullLogo.png" alt="TechWave Logo"></a>
</div>
<header>
    <div class="menu">
        <nav>
            <ul class="nav-menu">
                <li><a class="nav-link" href="index.php"><span id="home">Home</span></a></li>
                <li><a class="nav-link" href="jobs.php"><span id="careers">Careers</span></a></li>
                <li><a class="nav-link" href="apply.php"><span id="join-us">Join Us</span></a></li>
                <li><a class="nav-link" href="about.php"><span id="about-us">About Us</span></a></li>
                <li><a class="nav-link" href="enhancements.php"><span id="enhancements">Enhancements</span></a>
                </li>
            </ul>
        </nav>
        <a class="button" href="mailto:103076428@student.swin.edu.au">
            <span id="contact-us">Contact Us</span>
        </a>
    </div>
</header>