<h1>HR Management Portal</h1>
<div id="hr-actions">
    <a class="manage-buttons" href="displayEOIs.php"><span id="display-eois">Display EOI Applications</span></a></a>
    <a class="manage-buttons" href="deleteEOIs.php"><span id="delete-eois">Delete EOI Applications</span></a></a>
    <a class="manage-buttons" href="updateEOIStatus.php"><span id="update-eois">Update the Status of EOI Applications</span></a></a>
</div>