<header>
    <div class="menu">
        <nav>
            <ul class="nav-menu">
                <li><a class="nav-link" href="index.php"><span id="home">Home</span></a></li>
                <li><a class="nav-link" href="jobs.php"><span id="careers">Careers</span></a></li>
                <li><a class="nav-link" href="apply.php"><span id="join-us">Join Us</span></a></li>
                <li>
                    <a class="nav-link has-child"><span id="about">About</span></a>
                    <ul class="sub-menu">
                        <li><a href="about.php">About Us</a></li>
                        <li><a href="aboutMe.php">About Me</a></li>
                    </ul>
                </li>
                <li>
                    <a class="nav-link has-child" href="manage.php"><span id="manage">Manage EOIs</span></a>
                    <ul class="sub-menu">
                        <li><a href="displayEOIs.php">Display</a></li>
                        <li><a href="deleteEOIs.php">Delete</a></li>
                        <li><a href="updateEOIStatus.php">Update Status</a></li>
                    </ul>
                </li>
                <li>
                    <a class="nav-link has-child"><span id="enhancements">Enhancements</span></a>
                    <ul class="sub-menu">
                        <li><a href="enhancements.php">HTML & CSS</a></li>
                        <li><a href="enhancements2.php">JavaScript</a></li>
                        <li><a href="phpenhancements.php">PHP & MySQL</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <a class="button" href="mailto:103076428@student.swin.edu.au">
            <span id="contact-us">Contact Us</span>
        </a>
    </div>
</header>